# Generated by Django 5.2 on 2026-07-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='service',
            field=models.IntegerField(),
        ),
    ]
