# Generated by Django 5.2 on 2026-07-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='choices',
            new_name='cuisine_choices',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='delivery',
            new_name='has_delivery',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='network',
            new_name='has_wifi',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='hours',
            new_name='opening_hours',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='service',
            new_name='specialty',
        ),
        migrations.AddField(
            model_name='listing',
            name='accepts_reservatioms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='ambiance_note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='contant_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='promo_badge_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
