# Generated by Django 5.2 on 2026-07-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_choices_listing_cuisine_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='accepts_reservatioms',
            new_name='accepts_reservations',
        ),
    ]
