# Generated by Django 5.2 on 2026-07-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_accepts_reservatioms_listing_accepts_reservations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-list_date']},
        ),
    ]
